name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    strategy:
      fail-fast: true
      matrix: 
        version: ["1.14", "1.15"]
        system: [ubuntu-latest]

    runs-on: ${{ matrix.system }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.version }}
      - run: go test
      - run: go run main.go
      - run: echo "Action Executed."
