name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    strategy:
      fail-fast: true
      matrix: 
        version: ["1.14", "1.15"]
        system: [ubuntu-latest]

    runs-on: ${{ matrix.system }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.version }}
      - run: go test ./...
      - run: go run main.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: jeanduarte00/math-app-go-test:latest
