name: ci-golang-workflow
on: 
  push:
    branches:
      - "feature-**"
      - 'release-**'
  pull_request:
    branches:
      - develop
      - main
jobs:
  image-generation:
    strategy:
        fail-fast: true
        matrix: 
          version: ["1.15"]
          system: [ubuntu-latest]
    runs-on: ${{ matrix.system }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: jeanduarte00/math-app-go-test:latest

  check-application:
    strategy:
      fail-fast: true
      matrix: 
        version: ["1.15"]
        system: [ubuntu-latest]

    runs-on: ${{ matrix.system }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - run: go test -coverprofile=coverage.out
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.INFO_GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}